services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: submarine-frontend
    container_name: submarine-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - node_modules:/app/node_modules
    restart: always
    tty: true
    stdin_open: true

volumes:
  node_modules:
